### ISSUE TITLE
install an es plguin (elasticsearch-mapper-attachments) into the grails plugin

### ISSUE THREAD

**Issue by clessiomendes** [noamt/elasticsearch-grails-plugin#164]
Hi there. I'm restricted to use the plugin in "embedded" mode ( `client.mode = 'local';` ) and I would like to install the [elasticsearch-mapper-attachments](https://github.com/elastic/elasticsearch-mapper-attachments) in my hosting grails application. I've installed the mentioned plugin in ELASTIC_SEARCH_HOME with all the necessary libs, but how could I move them to my grails app and which change should I take to enable the plugin locally?

**Comment by marcoscarceles** [comment]
Hi @clessiomendes !

The plugin allow using  `elasticsearch-mapper-attachments` OOTB. It is loaded here:
https://github.com/noamt/elasticsearch-grails-plugin/blob/master/src/main/groovy/grails/plugins/elasticsearch/ClientNodeFactoryBean.groovy#L203

It should be included in the classpath, thanks to:
https://github.com/noamt/elasticsearch-grails-plugin/blob/master/build.gradle#L91

Since our integration tests indicate that loading the plugin works as expected. Can you send us a code example and the error message you're getting?
