### ISSUE TITLE
Support for indexing transient properties ?

### ISSUE THREAD

**Issue by v1p** [noamt/elasticsearch-grails-plugin#37]
Transient properties if supported, can help in reducing the mapping complexity and give a great handle on keeping the mapping of indices cleaner, without making all of the other domain classes searchable.
e.g User has Rating, where Rating is transient & is fetched through a service, as rating is necessarily calculated as average of all available ratings.
I tried the approach mentioned here :
https://github.com/mstein/elasticsearch-grails-plugin/issues/17

But I have hit a roadblock, it seems a valid hibernateSession + service dependecy Injection is required inside the scope of plugin. 
As soon as my transient property is reached, I get this error

``` groovy
| Error 2014-06-12 22:52:08,238 [localhost-startStop-1] ERROR hibernate.AssertionFailure  - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
Message: null id in User entry (don't flush the Session after an exception occurs)
    Line | Method
->>   70 | getRating                      in User
```

Any help would be great.

**Comment by nmfisher** [comment]
Have you had any luck mapping a transient collection of domain classes? I know the docs say that you can achieve this by defining the domain class in "hasMany" but this is just throwing the error that the dependent mapping is not injected.

More specifically, say I have three domain classes - Author, Book, AuthorBooks. Author<->Book is a bidirectional many-to-many relationship, mapped by a join table AuthorBooks (so we can add/delete an Author<->Book relationship without loading all of an Author's books into memory, or vice versa).

I override the getBooks/getAuthors methods to query the AuthorBooks table. For example:

class Author {

public Set<Book> getBooks() { 
        return DocumentProject.findAllByProject(this).collect { it.document } as Set
}

 This is exactly the same as the User<->Role (mapped by UserRole) relationship used in the spring security core plugin. Using normal GORM without elasticsearch, I don't need to define this under hasMany and it works fine.

However, once I start trying to map the domain for elasticsearch indexing, the plugin isn't able to determine the mapped property type. So this does not work:

class Author {
static searchable = {
only = ["books"]
books component:true
}

def getBooks() { // }

}

According to the docs, I should be able to define hasMany to play nice with ES (though this would require me to also define books as transient to stop GORM trying to persist books, as we persist this through an overriden addToBooks method:

class Author {

static hasMany = [books:Book]
static searchable = {
only = ["books"]
books component:true
}
static transients = ['books']

def getBooks() { // }
}

Still the same problem, when ES tries to map the property books, I get an IllegalStateException (component or reference, makes no difference). 

Any ideas?

**Comment by v1p** [comment]
try wrapping the content of your transient property's getter in a 
```
withNewSession{
...
}
```
Although I haven't tried a case where the transient property will be a collection. The correct type of such kind of mapping has to be 'nested'. Which I doubt if the current plugin supports for a transient mapping, as all transients are mapped as 'object' by default with this plugin.

**Comment by nmfisher** [comment]
No luck unfortunately. I don't think it's getting as far as calling the getter itself, SearchableClassPropertyMapping simply can't see that books is an association if it's transient (even when explicitly declared with Set<Book> books and hasMany).

I wonder if this is because the plugin relies on GrailsDomainClassProperty to determine if a property is an association, which is returning false if it's a transient collection? I'll play around further, I'm sure there is a way to achieve what I need.

**Comment by v1p** [comment]
of course! Please do share your approach on this.

**Comment by v1p** [comment]
```
When transient properties are collections the only way the plugin can define the correct ElasticSearch mapping during boot is if the element types are explicitly defined on the grails domain object. For instances of Collection this can be achieved by defining its type on the hasMany property (otherwise the ElasticSearch type will be defined as object). This is not required for arrays.
```
Doesn't work, @nmfisher Please make a new issue for this.

What's happening in this case is, the 'type' in the mapping is not set to anything (I thought it'll be nested, but it's set to nothing)

**Comment by nmfisher** [comment]
I actually got this working today* by modifying ElasticSearchMappingFactory, SearchableClassMappingConfigurator and SearchableClassPropertyMapping - at which point I started thinking that this is not actually a good idea at all for my application.

The whole point of mapping the join table is to avoid loading every associated record whenever you want to add to/remove from the join table, right? So if you want to add an author to a book, you just create a single entry in the join table, rather than loading one author and the entire collection of books, adding one to the collection, then saving the author.

However, ES does not know about the join table. It only knows that there is an author with a collection of books, or a book with a collection of authors. So if you want to create a new entry on the join table and have this association searchable via ES, you need to reindex the author instance with all of its associated books. But the only way to index the associated books is to fetch them all from the database again to insert them into the index - which is precisely the issue you were trying to avoid in the first place. Unless you want to go through the hassle of manually adding/deleting from a document's nested components (which probably isn't even possible via the vanilla grails plugin), it seems there isn't much benefit** to me in adopting this approach.

If this isn't correct, please anyone feel free to jump in and correct me.

The only suggestion I would have is to update the docs to make it clear that transient collections are only supported for basic types, not domain classes. I can post the modifications I used to support domain classes, but it's fairly ugly and (as explained above) I don't think it's actually a useful feature.

* Note 1 - for anyone who does want to go ahead with this approach, there's a small Hibernate specific issue. When ES returns a result, the plugin rebuilds the domain instance from the index. I think the rebuilt instance is not attached to a Hibernate session and is therefore transient, so if you try and use a dynamic finder with this object, you'll get a TransientObjectException. Any queries should be based on the object's ID.

** Note 2 - there is probably a use case if it's OK for your ES index to be updated separately from your database (say, overnight when there are few users and the load is minimal). For example, a user could create a new AuthorBook entry in the database (which doesn't load all associated books) at 1pm, then at 2am the ES index is updated (which does need to load all associated books). I need my index to be updated in realtime, so this doesn't help me.

**Comment by addmaths07** [comment]
Facing a similar problem as described above by @nmfisher, should I open a new issue? 
@nmfisher can you please share the changes you made to make it work?

**Comment by nmfisher** [comment]
@addmaths07 As mentioned, I didn't go ahead with this as I'm pretty sure there was no benefit (for me at least). Are you really sure you need to index transient hasMany collections? Can you explain what are you trying to achieve?

**Comment by addmaths07** [comment]
Here is my case:
There are members who can create variety of content (questions, attachments, events), member itself can have multiple attributes and properties. 

I couldn't use actual member domain since I only wanted to keep immediate properties of member in the domain.

**Comment by addmaths07** [comment]
Here is my case:
There are members who can create variety of content (questions, attachments, events), member itself can have multiple attributes and properties.

I have to match members against a query.

These are the domains:
MemberRecord {
static searchable = {
only = ["questions", "answers", "polls", "reviews", "attributes "]
questions component:true
answers component:true
polls component:true
reviews component:true
attributes  component:true
}

static mapping = {
	version		false
	id 			generator:'assigned', column:'member_id'
}
static transients = ["questions", "answers", "polls", "reviews", "attributes "]

List<MemberData> getQuestions( // gets all entries for type question using MemberData.findAllBy)
List<MemberData> getAnswers(// gets all entries for type answers using MemberData.findAllBy)
List<MemberData> getPolls (// gets all entries for type polls using MemberData.findAllBy)
List<MemberData> getReviews (// gets all entries for type reviews using MemberData.findAllBy)
List<MemberData> getAttributes  (// gets all entries for type attributes using MemberData.findAllBy )
}

MemberData{
    Long refId // id of actual content
    String text
    String type // type of content

   static belongsTo = [parentRecord: MemberRecord]
}
With this mapping I expect elasticsearch to create nested mapping for MemberRecord and MemberData.
Benefit of above approach is, gorm only creates two table MemberRecord and MemberData and I run a job, containing independent sql scripts which populate data in MemberRecord and MemberData and then index all of it.

I plan to run this job only one time or for backup purposes only. Once the existing data has been indexed, I will take advantage of groovy script support in elasticsearch to add/edit/delete entries on joined table i.e MemberData for existing members.

I somehow managed to index the data after making some insane changes in SearchableClassMappingConfigurator and other classes, but now facing an issue on retrieving the results (DomainUnmarshaller is taking considerable amount of time to unmarshall the search hits).

P.S I couldn't use actual member domain since I only wanted to keep immediate properties of member in the domain to keep it light.

**Comment by nmfisher** [comment]
MemberData already contains the relevant type (question, answer, poll, etc). Why couldn't you just use hasMany [memberData:MemberData] (non-transient), and then your ES query can search for MemberRecords based on the MemberData nested type.

You'd probably need to change the mapping for MemberRecord so that it uses a key on the child table, rather than a separate join table. 

Wouldn't this be a lot better than hacking something together inside the ES plugin?

**Comment by addmaths07** [comment]
Well to be honest, didn't think about it, let me try it out to see what changes are required in overall design. 
The reason for keeping separate fields for each type in MemberData, is to make boosting level configurable for each type, plus it simplifies the schema for MoreLikeThis query to run on MemberRecord.

**Comment by addmaths07** [comment]
Other approach could be to maintain hasMany <contentType>:MemberData,  relationship with all the contents of member. This would create a sparse association table maintaining relationships of different content types with MemberRecord. 
Impact of the approach:
- will increase the complexity of sql scripts that I use to populate the data
- adding new content type will have change in the association table

Good thing would be, there won't be any transient properties to bother.

**Comment by nmfisher** [comment]
If you want to be able to boost based on nested object fields, you could have transient boolean properties like isQuestion/isAnswer in your MemberData class (i.e. using a getter only like getIsQuestion()/getIsAnswer() etc), and then index/boost those.

**Comment by marcoscarceles** [comment]
Effectively, the transients mapping do not work with collections of components. I think I've found a fix for this and I will be submitting it asap, alongside an example application and improved docs.

Cheers

**Comment by nmfisher** [comment]
So turns out I did have a use case for this, so I've submitted a pull request based on the latest development snapshot. If anyone needs this functionality, please give it a try and let me know.
